"""empty message

Revision ID: 40688d8aace2
Revises: e3bbc00b409c
Create Date: 2020-04-14 09:22:51.133760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40688d8aace2'
down_revision = 'e3bbc00b409c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')

    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
